spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5439/test
    username: test
    password: test
    initialize: true

  jpa:
    hibernate:
      ddl-auto : create

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/docs

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  httpexchanges:
    recording:
      enabled: false