springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/docs

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus
  httpexchanges:
    recording:
      enabled: false